<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="efeu">
<!--_____________________________________________Fahrwerk 1 - Link____________________________________________________________________-->
  <link name="link_fahrwerk1">
    <!-- pose and inertial -->
     <inertial>
    <origin xyz="0 0 ${d_Rad/2+z_h_klein_Fw1/2}" rpy="0 0 0"/>
      <mass value="${m_Fw1-2*m_Rad}"/>
      <origin rpy="${x_offset_Fw1} ${y_offset_Fw1} ${z_offset_Fw1}" xyz="0 0 0"/>	
      <inertia ixx="${Ixx_Fw1}" ixy="${Ixy_Fw1}" ixz="${Ixz_Fw1}" iyy="${Iyy_Fw1}" iyz="${Iyz_Fw1}" izz="${Izz_Fw1}"/> 
    </inertial>	
<!--Collision-->
    <collision name="collision_fahrwerk1">
      <origin xyz="0 0 ${d_Rad/2-z_h_klein_Fw1/2}" rpy="0 0 0"/>	
      <geometry>
        <mesh filename="package://urdf_viewer/meshes/efeu_fahrwerk1_visual.dae" scale="1 1 1"/> 
      </geometry>
    </collision>
 <!--Visual-->
    <visual>
      <origin xyz="0 0 ${d_Rad/2-z_h_klein_Fw1/2}" rpy="0 0 0"/>	
      <geometry>
       <mesh filename="package://urdf_viewer/meshes/efeu_fahrwerk1_visual.dae" scale="1 1 1" />
      </geometry>
     </visual>
     </link>

     <!--_________________________________________________Pendelachse - Link________________________________________________________________-->
<link name="link_pendelachse">
    <!--inertial -->
      <inertial>
      <mass value="${0.1}"/>
     <inertia ixx="${0.0001}" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/> 
    </inertial>	
<!--Collision-->
    <collision name="collision_pendelachse">
     <origin xyz="0 0 -0" rpy="0 0 0" />
     <geometry>
       <mesh filename="package://urdf_viewer/meshes/efeu_Pendelachse.dae" scale="1 1 1"/> 
     </geometry>
    </collision>
 <!--Visual-->
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
       <mesh filename="package://urdf_viewer/meshes/efeu_Pendelachse.dae" scale="1 1 1" />
      </geometry>
     </visual>
</link>
<!--_________________________________________________Fahrwerk 2 - Link________________________________________________________________-->
<link name="link_fahrwerk2">
    <!--inertial -->
      <inertial>
      <mass value="${m_Fw2}"/>
     <origin xyz="${x_offset_Fw2} 0 ${z_offset_Fw2-0.006}" rpy="0 0 ${Math_pi/2}"/><!--	Massenschwerpunkt-->
     <inertia ixx="${Ixx_Fw2}" ixy="${Ixy_Fw2}" ixz="${Ixz_Fw2}" iyy="${Iyy_Fw2}" iyz="${Iyz_Fw2}" izz="${Izz_Fw2}"/> 
    </inertial>	
<!--Collision-->
    <collision name="collision_fahrwerk2">
     <origin xyz="0 0 -0.006" rpy="0 0 0" />
     <geometry>
       <mesh filename="package://urdf_viewer/meshes/efeu_fahrwerk2_collision.dae" scale="1 1 1"/> 
     </geometry>
    </collision>
 <!--Visual-->
    <visual>
     <origin xyz="0 0 -0.006" rpy="0 0 0" />
      <geometry>
       <mesh filename="package://urdf_viewer/meshes/efeu_fahrwerk2_visual.dae" scale="1 1 1" />
      </geometry>
     </visual>
     </link>
<!--__________________________________________Gelenke zwischen Fahrwerk 1 und Fahrwerk 2_______________________________________________________________________-->   
<joint name="fahrwerk_pendel_joint" type="continuous">
    <parent link="link_fahrwerk1" />
    <child link="link_pendelachse" />
    <origin xyz="${-x_l_Fw1} 0 ${d_Rad/2-z_h_klein_Fw1/2+z_Pendelachse/2}" rpy="0 0 0" />
    <axis xyz="1 0 0"/>
    <dynamics damping="${daempfung_pendel_joint}" friction="${friction_pendel_joint}"/>
 </joint>

  <joint name="fahrwerk_knick_joint" type="revolute">
    <parent link="link_pendelachse" />
    <child link="link_fahrwerk2" />
    <origin xyz="${-x_Pendelachse} 0 ${-z_Pendelachse/2}" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <dynamics damping="${daempfung_knick_joint}" friction="${friction_knick_joint}"/>
    <limit effort="1000" lower="${-Math_pi/6}" upper="${Math_pi/6}" velocity="1000"/>
    
  </joint>

<!--_______________________________________________________________________________________________________________-->  
<transmission name="trans_knick">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fahrwerk_knick_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_knick">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> 
</robot>
